name:                pb-haskell
version:             0.1.0.0
github:              edilmedeiros/pb-haskell
license:             BSD-3-Clause
author:              Edil Medeiros
maintainer:          jose.edil+pbhaskell@gmail
copyright:           Edil Medeiros 2023

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/edilmedeiros/pb-haskell#readme>

dependencies:
- base >= 4.11 && < 10
- rio >= 0.1.12.0

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  pb-haskell:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - pb-haskell
    - optparse-simple

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

tests:
  pb-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - pb-haskell
    - hspec

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
